'use server';
/**
 * @fileOverview An AI assistant that generates comprehensive task descriptions for NGO Admins.
 *
 * - generateNGOTaskDescription - A function to generate a detailed task description based on brief input.
 * - NGOTaskDescriptionGeneratorInput - The input type for the generateNGOTaskDescription function.
 * - NGOTaskDescriptionGeneratorOutput - The return type for the generateNGOTaskDescription function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const NGOTaskDescriptionGeneratorInputSchema = z.object({
  briefDescription: z.string().describe('A brief overview of the task, provided by the NGO Admin.'),
  requiredSkills: z.array(z.string()).optional().describe('Optional: Specific skills required for volunteers to complete the task.'),
  location: z.string().optional().describe('Optional: The geographical location where the task needs to be performed.'),
  urgency: z.enum(['normal', 'urgent', 'emergency']).optional().describe('Optional: The urgency level of the task.'),
  expectedDuration: z.string().optional().describe('Optional: The estimated time required to complete the task (e.g., "4 hours", "2 days").'),
  materialsNeeded: z.array(z.string()).optional().describe('Optional: A list of materials or equipment volunteers might need.'),
});
export type NGOTaskDescriptionGeneratorInput = z.infer<typeof NGOTaskDescriptionGeneratorInputSchema>;

const NGOTaskDescriptionGeneratorOutputSchema = z.object({
  detailedDescription: z.string().describe('A comprehensive, clear, and well-structured task description generated by the AI assistant.'),
});
export type NGOTaskDescriptionGeneratorOutput = z.infer<typeof NGOTaskDescriptionGeneratorOutputSchema>;

export async function generateNGOTaskDescription(
  input: NGOTaskDescriptionGeneratorInput
): Promise<NGOTaskDescriptionGeneratorOutput> {
  return ngoTaskDescriptionGeneratorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'ngoTaskDescriptionPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: { schema: NGOTaskDescriptionGeneratorInputSchema },
  output: { schema: NGOTaskDescriptionGeneratorOutputSchema },
  prompt: `You are an AI assistant specialized in generating clear, comprehensive, and well-structured task descriptions for NGOs. Your goal is to help NGO Admins efficiently communicate all necessary details to volunteers based on minimal input.

Generate a detailed task description using the following information. Ensure the description is easy to understand, covers all critical requirements, and motivates volunteers.

Brief Task Overview: "{{{briefDescription}}}"

{{#if requiredSkills}}
Required Skills:
{{#each requiredSkills}}
- {{{this}}}
{{/each}}
{{/if}}

{{#if location}}
Location: {{{location}}}
{{/if}}

{{#if urgency}}
Urgency: {{{urgency}}}
{{/if}}

{{#if expectedDuration}}
Expected Duration: {{{expectedDuration}}}
{{/if}}

{{#if materialsNeeded}}
Materials Needed:
{{#each materialsNeeded}}
- {{{this}}}
{{/each}}
{{/if}}

Please structure your response as a comprehensive task description, starting with a concise summary, followed by a clear breakdown of responsibilities, requirements, and any other pertinent information. Highlight the impact of the task.`,
});

const ngoTaskDescriptionGeneratorFlow = ai.defineFlow(
  {
    name: 'ngoTaskDescriptionGeneratorFlow',
    inputSchema: NGOTaskDescriptionGeneratorInputSchema,
    outputSchema: NGOTaskDescriptionGeneratorOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
